      program happybirthday
          print *, "Hello World!"
          print *, "***************************************************"
          print *, "*                                                 *"
          print *, "*                                                 *"
          print *, "*                 Happy Birthday!                 *"
          print *, "*                                                 *"
          print *, "*                                                 *"
          print *, "***************************************************"
          print *, "CCCLLfffffffLLLLLfffffffftttttttfLLLCCCCLLLCLLLLLCC"
          print *, "tt11111111ttffffffLCCCCCLLLfft111tfLLLLLLLfftfLLLLL"
          print *, "1111111tfffffttfCG0GGCCLLLCCLfLLfffLfffLLfft11fLLLf"
          print *, "tttftttfffftttCGGGLffffffffLfLLLLLLLffffttffftfffff"
          print *, "ffffffftttttLGCCCfttttt1tffffffLfffLftt111tffffffff"
          print *, "tttttttttttfCffft11111tfLCCGGCLfLffLLLfttttttttttff"
          print *, "LLLffffttttCLfLftttfffLCGGGG00GLLCLLCLLffffffffffff"
          print *, "LLLLLLfftttCLGCCCCCGGGGGGGGGG00GLCCCCLLLLLLLLLLLLLL"
          print *, "LLLLLLLLLLLCLGCCCCCCGGGGGGGGGG0GGCLCCCCLLLLLLfffLLL"
          print *, "GCCLLLLCLLfLfLCCGGGGCCCCGGGGGG0000CCCGCLLLLLLLLLLLL"
          print *, "GGCCCLLLLfffLLGCCCLLLLLLftt1tffCG00CCLCLLCCCLCCGGGC"
          print *, "CLLLLLLLLLLLLCCt11111fLLt11tfLLCG00GGCCLLLCLfLLLLLL"
          print *, "LLLLfffLffLLfCCfttttffGGCCCCCGGGG00GG0CLLLftttfffft"
          print *, "LfLLLCCCCCLLCCGGGCCCLLG00GCLCCCGGGGGCLLLLLLLLLLCLLL"
          print *, "ffLLCCCCCCCCLLCCCCCLfLCGGGCLLLLLCCGGG0GLLLfffffffLL"
          print *, "LLLLLLfLLLLLLLLCLLffLLtttffLLffLCLCGGG@80000GG0GLLL"
          print *, "LLLLLLfLLLLLCCCLLffffffttffLCLffLLCGGL88888@8@88@88"
          print *, "LLLLLLLLLLffLLLfffftfLLLffLCCCLffLLGCL88880808808@@"
          print *, "LLLLLLLLLLLLLLLC08GftfLCCCCCLLffffLCLC888888000G088"
          print *, "fffLLLLLLCCLCG888880CttttttttttffLLLLG088880800G088"
          print *, "ffffffLLLLCG888800800LfftttttttffLffCLfLCG0G000G000"
          print *, "LLLffLLLC08@8000008000CLttffffffffLCCLLLLC00000GG00"
          print *, "fffLLLC08@880000008880GGCffffffffCGCCGCCGG00000GG00"
          print *, "LLLLC08@88880000000GCLfLGGCCCCLfCGGGGGCGGG000000GGG"
          print *, "CCC0888888880000000CCCCLLCCCCCGGCG000GGGGGG00000GGG"
          print *, "***************************************************"
          print *, "*                                                 *"
          print *, "*                                                 *"
          print *, "*                 Happy Birthday!                 *"
          print *, "*                                                 *"
          print *, "*                                                 *"
          print *, "***************************************************"
      end program happybirthday
