      program happybirthday
          print *, "ZZZZOOZZZZOZOOZZZOOZZZOOOOO888OZZZZ$$$ZZ$$$$$77777Z"
          print *, "ZZZZZZZ$$$ZOZZO888OZZOOOZZ$7$Z$$ZZ$DDDDDDDOZ$77777Z"
          print *, "ZZZZZZ$$$$ZOZ8OOO$Z$$7III??+??II$ZZOODDDD8D8$777I7Z"
          print *, "ZO$ZZZZ$$$ZZOOZOO$7?++++======++?I7ZZODDDDD8$77777Z"
          print *, "$ZZZZZZZ$$ZOZZZ7I???+==~~~~~~~~~==+??$O8DDD8Z77II7Z"
          print *, "ZZ$ZZZZ$$$Z$7$7II?++=~~:,,,:::::~~=+?I7$DDDDZ7I77IZ"
          print *, "ZZ$ZZZ$$$OO77??III+=~~~::::::::~~~~=+II7DDDDO$77IIZ"
          print *, "ZZ$ZZZ$$$ZOII+?I??+~~~~~~~~~~:~~=~~=+I7I8DDD8ZIIIIO"
          print *, "ZZ$ZZZ$$$$$I?+???++~~~~~:~:~~~~~~~~=+I7I8D8D8Z7IIIZ"
          print *, "ZZ$ZZZ$$$$$II+++++?=~::~~:::~:::~==~~+I?$88DO7IIIIO"
          print *, "ZZ$ZZ$$$7$$I???+++?=~~:~~~~~~~~=+?III7$IZ888ZIIIIIO"
          print *, "$$$$$$$$$777I??++??==:,:,==~~~~===+???77?$88Z7IIIIO"
          print *, "$$$Z$$$$77$77?+++?7?+?=++++=:~?+=?I?I+IZ?7D8ZIIIIIO"
          print *, "$Z$$$$$$777+=++$7+I+=++===+I+=?+=~~==+?+=O88$IIII78"
          print *, "$$$$$$$7777==++=?+?++==~~~~?+~++=~~===++I88O$777Z8N"
          print *, "$Z$$$$$$777==++=++++=~~====++~=+=~~~~=+I?8888OO8DDN"
          print *, "$Z$$$$$7777===+III?+=~~~~~~?=~~++:~~~=?+78DDDD88D$$"
          print *, "$$$$$$$$7777=~=IIII+=~~~:~~++~:++=~~=++=O88DDD8ZI7I"
          print *, "$$$$$$$$777$7I=??I+?+==~~~~~:::~~~~~~~?8$$7I++??II?"
          print *, "Z$$$$$$$777$$$$$II+?+++~~~~::::~==+~~~?$II7I==??II?"
          print *, "8Z$$$$$7777$$$$$II+?++=~~~~~~=~+???=~~?7?+I?=+??II?"
          print *, "DDDOZ$$$777$$ZO87I?+?++:~~~~~~~~~===~~?????????III?"
          print *, "NDDDDD$$$ZZ8888I~?+=?===~~~~~~~~~~~~=?I++??++III?++"
          print *, "NNDNDD8OO88DD8O~~~===?=+=~~~~~~:~~~~+7I++++++?II+++"
          print *, "NNDNDDDDDD88OOZ~:::===+=+=~~~~::~:~=?I++++++???+==?"
          print *, "NNNNNND88OOOOOZ8$:,,,:~=++?+==?=+I7D?+++++=+++====+"
          print *, "NDD88O8OOOZOZOO888~,,,,::~~~~:~+II+:8+++++====+===?"
          print *, "888O88OOZZOOOZZZO88O,,,,,,,~~=++++~:O8?===++==~=~=I"
          print *, "88O88OOOOZOOZZZZZ88DO,,,,,,::~~===~~Z88?~+?+==~===I"
          print *, "OO8OO8OOZOOZOZZZZZO888D,,,,,.O8D$,,~OOOOZOZZO$====I"
          print *, "OZOOOOOZZZZOOZZZZ$Z8D88Z,,,,,ID8$,,~+ZZOOZZZZZZZ7~7"
          print *, "ZZZZZZZZZZOZZZZZ$ZZZD8888+,:,?O8=,,::$$OOOZZZ$ZZZO7"
          print *, "ZZZZZZZZZ$$$ZZ$Z$Z$$Z888888,,888O,,,:Z$OOZZZZZ$ZZZI"
          print *, "ZZZZZZOZZ$$Z$$$$$$$$Z8888O8,.8888,,,:Z$ZOOOZZ$$ZZ$O"
          print *, "ZZZ$ZZZZZ$$Z$$$$$$$ZZZ8D8888:8D88D,::O$ZOOZZZZZZZ7O"
          print *, "                         * * *                     "
          print *, "John Warner Backus  (December 3,  1924 - March  17,"
          print *, "2007)  was an  American   computer  scientist.   He"
          print *, "directed the team  that invented  the first  widely"
          print *, "used high-level programming language (FORTRAN)  and"
          print *, "was the inventor  of the  Backus-Naur form (BNF), a"
          print *, "widely  used notation  to define  formal   language"
          print *, "syntax.   He also did    research in function-level"
          print *, "programming and helped to popularize it."
          print *, "                                        --Wikipedia"
        end program happybirthday
